apiVersion: apps/v1
kind: Deployment
metadata:
  name: adok8-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adok8
  template:
    metadata:
      labels:
        app: adok8
        version: adok8-version-1
    spec:
      containers:
        - name: adok8-1
          image: dockerimage
          imagePullPolicy: Always
          ports:
          - containerPort: 9999
         
