apiVersion: v1
kind: Service
metadata:
  name: adok8
spec:
  type: LoadBalancer
  ports:
  - port: 9999
    targetPort: 9999
    protocol: TCP
    name: http
  selector:
    app: adok8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adok8-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adok8
  template:
    metadata:
      labels:
        app: adok8
        version: adok8-version-1
    spec:
      containers:
      - name: adok8-1
        image: 670166063118.dkr.ecr.us-east-1.amazonaws.com/eksdemo:qa-release1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m 
        env:
           - name: TZ
             value: Asia/Kolkata      
